---

# Create a service that is used for discovery of hazelcast nodes
apiVersion: v1
kind: Service
metadata:
  name: bridge-hazelcast-service
spec:
  selector:
    app.kubernetes.io/name: kafka-bridge
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    strimzi.io/kind: KafkaBridge
  ports:
  - name: hazel
    port: 5701
    protocol: TCP

---

# Grant permission to kafkabridge pods to monitor the API server for changesm. Needed for the discovery of Hazelcast nodes
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: strimzi-bridge
  namespace: kafka
